version: '3.8'
services:
  node:
    container_name: ${NODE_SERVER_HOST}
    image: node:${NODE_VERSION}
    user: ${NODE_USER}
    working_dir: /home/node/app
    environment:
      - NODE_SERVER_PORT=${NODE_SERVER_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/home/node/app
    ports:
      - ${NODE_FORWARD_PORT}:${NODE_SERVER_PORT}
    command: "npm start"
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: ${DB_HOST}
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - my_network
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
      - 'node_db_volume:/var/lib/mysql'
    healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--password=${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
  my_network:
    driver: bridge

volumes:
  node_db_volume:
    driver: local