on:
  push:
    branches: [ "ci" ]

env:
  NODE_VERSION: '18.13.0'
  SERVER_USER: 'MOONSCAPE'
  SERVER_URL: 'ecv-etic.upf.edu'
  SERVER_DEPLOY_PATH: '/home/MOONSCAPE/p2/backend'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
    
    - name: Install sshpass
      run: |
        sudo apt-get install sshpass

    - name: 'Deploy to UPF server'
      run: |
        sshpass -p ${{ secrets.SERVER_PASS }} scp -r -o StrictHostKeyChecking=no . MOONSCAPE@ecv-etic.upf.edu:/home/MOONSCAPE/p2/backend
