on:
  push:
    branches: [ "ci" ]

env:
  NODE_VERSION: '18.13.0'
  SERVER_USER: 'MOONSCAPE'
  SERVER_URL: 'ecv-etic.upf.edu'
  SERVER_DEPLOY_PATH: '/home/MOONSCAPE/p2/backend'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ECV_UPF_SERVER_SSH_PRIVATE_KEY }}
        known_hosts: "random_dont_worry"
    
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ env.SERVER_URL }} >> ~/.ssh/known_hosts

    - name: 'Deploy to UPF server'
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ECV_UPF_SERVER_SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ env.SERVER_URL }}
        REMOTE_USER: ${{ env.SERVER_USER }}
        TARGET: ${{ env.SERVER_DEPLOY_PATH }}
        EXCLUDE: ".git*, .env_example"
